### ISSUE TITLE
Bug inside 1.3.1 - delete a (form-) field

### ISSUE THREAD

**Issue by aldus** [WebsiteBaker-modules/mpform#1]
Try to delete an existing field of a form in the backend-interface results in a js-alert »Post arguments missing« - instead of executing the //delete//.

WebsiteBaker 2.8.3 - SP7
PHP 7.0.12 - Iron (53.0.2800.0)

**Comment by mrbaseman** [comment]
merged in the pull request

**Comment by mrbaseman** [comment]
sorry, I have clicked too fast. I'll draft a new release when I have implemented a few more fixes for the bugs reported in the forums recently.
