### ISSUE TITLE
no space between attributes

### ISSUE THREAD

**Issue by gitFrank** [WebsiteBaker-modules/mpform#4]
https://github.com/WebsiteBaker-modules/mpform/blob/fa9c9d5b33af0a42a16f99f2f129557edba65bd2/paintform.php#L770

HTML Validator want to see a space else he tells:
Error: No space between attributes.

There only a space before class is missing. All other attributes in paintform are correctly.

**Comment by mrbaseman** [comment]
I have just fixed this on master. I'm going to tag a new release soon (I'd like to fix a small ajax issue, too)
