### ISSUE TITLE
Styles and scripts gone in MPForm 1.3.22? (WBCE)

### ISSUE THREAD

**Issue by digitalbricks** [WebsiteBaker-modules/mpform#8]
Hello,

i recently updated some legacy versions of MPForm to the current 1.3.22 and noticed that the backend pages looks weird now (see attached screenshots). All the background color for the table views are gone and also the JS based functionality for sorting fields.

![bildschirmfoto 2018-06-01 um 10 01 47](https://user-images.githubusercontent.com/2983578/40832269-487bf7c8-658b-11e8-978f-cb6666c07d11.png)
![bildschirmfoto 2018-06-01 um 10 58 46](https://user-images.githubusercontent.com/2983578/40832272-4a7f45f2-658b-11e8-9dd1-b7d7ffe51e6b.png)

As i can see, the module `backend.css` and `backend_body.js` are loaded and i also have no error in the JS console.

But i am using WBCE instead of WebsiteBaker – maybe the problem arises because of that?

I appreciate any hints
André

**Comment by mrbaseman** [comment]
hmm... this looks like a style issue.

The style files are not replaced automatically during an update to prevent your local modifications from being overwritten. If you don't have any local style adjustments in the backend, you can try copying `backend.default.css` to `backend.css` (overwriting an old style file which might not work anymore as expected) and see if this solves the problem.

If not, which backend theme is this? I'm using wbce flat which works well, and I have just tried argos reloaded which also looks ok in my wbce 1.3.1

**Comment by digitalbricks** [comment]
Hello Martin,

great – you got the point: After i deleted the (old) `backend.css` and renamed the `backend.default.css` accordingly, everything is back and working as expected!

Thank you very much!
André

**Comment by mrbaseman** [comment]
so, I think we can close this issue
